server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://47.92.221.53/ddmeal?serverTimezone=GMT
    username: root
    password: 456722@Zjy
    driver-class-name: com.mysql.cj.jdbc.Driver


    # \u8FD4\u56DEjson\u7684\u5168\u5C40\u65F6\u95F4\u683C\u5F0F
  jackson.date-format: yyyy-MM-dd HH:mm:ss
  jackson.time-zone: GMT+8

